/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CyGraph: typeof import('./src/components/Graph/CyGraph/CyGraph.vue')['default']
    Graph: typeof import('./src/components/Graph/Graph.vue')['default']
    HKMap: typeof import('./src/components/HKMap/HKMap.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PreviousPath: typeof import('./src/components/Graph/PreviousPath.vue')['default']
    Progression: typeof import('./src/components/Graph/Progression.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Graph/Search.vue')['default']
  }
}
